import { Providers } from '@/redux/provider';  // Buat Provider untuk Redux
import { Header } from '@/components/Header';
import { Footer } from '@/components/Footer';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>  {/* Tambahkan Redux Provider */}
          <Header />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
